CREATE USER STERTWI
  IDENTIFIED BY Password1
  DEFAULT TABLESPACE APP
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for STERTWI 
  GRANT CONNECT TO STERTWI;
  GRANT RESOURCE TO STERTWI;
  ALTER USER STERTWI DEFAULT ROLE ALL;
  -- 4 System Privileges for STERTWI 
  GRANT CREATE VIEW TO STERTWI;
  GRANT UNLIMITED TABLESPACE TO STERTWI;
  GRANT CREATE ANY DIRECTORY TO STERTWI;
  GRANT QUERY REWRITE TO STERTWI;
  -- 1 Tablespace Quota for STERTWI 
  ALTER USER STERTWI QUOTA UNLIMITED ON APP;