ALTER TABLE STERTWI.PIANO
 DROP PRIMARY KEY CASCADE;

DROP TABLE STERTWI.PIANO CASCADE CONSTRAINTS;

CREATE TABLE STERTWI.PIANO
(
  ID               NUMBER                       NOT NULL,
  NOME             VARCHAR2(256 BYTE),
  LAST_UPDATE      DATE,
  STUDENTE         NUMBER,
  ORESTUDIOGIORNO  FLOAT(126)
)
TABLESPACE APP
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX STERTWI.PIANO_PK ON STERTWI.PIANO
(ID)
LOGGING
TABLESPACE APP
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER STERTWI.PIANO_TRG
BEFORE INSERT
ON STERTWI.PIANO REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DISABLE
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := PIANO_SEQ.nextval;
END PIANO_TRG;
/


CREATE OR REPLACE TRIGGER STERTWI.PIANO_UPDATE_TRG
before insert or UPDATE
ON STERTWI.PIANO FOR EACH ROW
BEGIN
  :new.last_update := systimestamp;
END PIANO_UPDATE_TRG;
/


ALTER TABLE STERTWI.PIANO ADD (
  CONSTRAINT PIANO_PK
  PRIMARY KEY
  (ID)
  USING INDEX STERTWI.PIANO_PK);

ALTER TABLE STERTWI.PIANO ADD (
  CONSTRAINT PIANO_STUDENTE_FK 
  FOREIGN KEY (STUDENTE) 
  REFERENCES STERTWI.STUDENTE (ID));
