DROP TABLESPACE APP INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE APP DATAFILE 
  'D:\APP\USER1\ORADATA\ORCLNEW\APP01.DBF' SIZE 20M AUTOEXTEND ON NEXT 20M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

